{% set name = "zeopp-lsmo" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lsmo-epfl/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 74ea4de20c18593564a1f74b7ea342903dce2de07be92d768e86c1d3db866521

build:
  number: 0

  skip: true  # [ win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - libtool
    - pytest
  host:
    - eigen >=3.2.8

test:
  source_files:
    - tests/
  commands:
    - network
    - voro++ -h
    - cd tests && pytest test_zeopp.py


about:
  home: https://github.com/lsmo-epfl/zeopp-lsmo
  license: LicenseRef-BSD-3-CLAUSE-ZEOPP
  license_family: BSD
  license_file: LICENSE
  summary: |
    Zeo++ (LSMO) - High-throughput analysis of crystalline porous materials
  description: |
    Zeo++ is a software package for high-throughput analysis of structure and topology of crystalline porous materials.
    Based on the Voronoi decomposition of the atomic structure, it calculates geometrical parameters describing pores, such as the diameter of the largest included sphere and the largest free sphere. 
    For a given guest molecule, it determines accessibility of nodes in the network, the dimensionality of channel systems as well as the distributions of accessible surfaces, volumes and pore sizes via Monte Carlo sampling.
    Originally developed by Maciej Haranczyk, Chris H Rycroft, Richard L Martin, Thomas F Willems, the LSMO fork of zeo++ adds bug fixes and new features.
    The LSMO fork of zeo++
  doc_url: https://github.com/lsmo-epfl/zeopp-lsmo
  dev_url: https://github.com/lsmo-epfl/zeopp-lsmo

extra:
  recipe-maintainers:
    - ltalirz
    - kjappelbaum
